src/cajn_site/urls.py
from django.urls import path
from .views import base_views as base, client_views as client, vehicle_views as vehicle, part_views as part

urlpatterns = [
    # visible page routes
    path(r'', base.home, name="cajn-site-home"),
    path(r'manage-clients/', base.ManageClients, name='cajn-manage-clients'),
    path(r'add-client/', client.AddClientView, name='cajn-add-client'),
    path(r'client-info/<int:client_id>', client.ClientManagePage, name='cajn-client'),
    path(r'add-vehicle/', vehicle.AddVehicleView, name='cajn-add-vehicle'),
    path(r'add-part/', part.AddPartView, name='cajn-add-part'),
    path(r'client-vehicle/<int:id>', client.AddVehicleClient_FormRequest),
    path(r'vehicle-info/<int:client_id>/<int:vehicle_id>', vehicle.VehicleInfoPage),
    path(r'work-done/<int:client_id>/<int:vehicle_id>', vehicle.AddWorkDone, name='cajn-work-done'),
    
    # This one will need to be updated when invoice generation is under development
    path(r'create-invoice/', base.CreateInvoice, name="cajn-site-create-invoice"),

    # add info to db routes
    path(r'DeleteClient/<int:id>', client.DeleteClient),
    path(r'EditClient/<int:id>', client.EditClient),
    path(r'AddVehicleClient/<int:id>', client.AddVehicleToClient),
]

src/cajnvoice/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cajn_site.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', users_views.Signout, name='logout'),
]

src/cajn_site/models.py
from django.db import models

class Parts(models.Model):
    part_name = models.TextField(blank=False)
    part_serial = models.TextField(blank=False)


class Vehicle(models.Model):
    vehicle_brand = models.TextField(blank=False)
    vehicle_type = models.TextField(blank=False)


class Clients(models.Model):
    client_f_name = models.TextField(max_length=20, blank=False)
    client_l_name = models.TextField(max_length=20, blank=False)
    client_email = models.TextField(blank=True)
    mailing_address = models.TextField(blank=False)
    postal_code = models.TextField(max_length=7, blank=False) # ADA DAD format required, 7 char max (includes space) 
    city = models.TextField(max_length=25, blank=False)
    vehicles = models.ManyToManyField(Vehicle, blank=True, unique=False)

    def First_Name(self):
        return self.client_f_name


class Vehicle_Work(models.Model):
    title = models.TextField()
    work_done = models.TextField(blank=True)
    last_service_date = models.DateField(blank=True)
    last_service_hours = models.PositiveIntegerField(blank=False)
    parts_id = models.ManyToManyField(Parts, blank=True, unique=False) # allow a list of parts to be added
    vehicle_id = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    client_id = models.ForeignKey(Clients, on_delete=models.CASCADE)

src/cajn_site/forms.py
from django import forms

class AddWorkDoneForm(forms.Form):
    last_service_date = forms.DateField(label="Date of last service (MM/DD/YYYY)") # see about changing the order of this
    last_service_hours = forms.IntegerField(label="Hours/KM since last service")
    work_done = forms.CharField(widget=forms.Textarea)

class AddPartForm(forms.Form):
    part_name = forms.CharField(label="Part Name")
    part_serial_num = forms.CharField(label="Serial Number")

class AddVehicleForm(forms.Form):
    vehicle_brand = forms.CharField(label='Vehicle Brand', max_length=25)
    vehicle_type = forms.CharField(label='Vehicle Type', max_length=25)

class AddClientForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=20)
    last_name = forms.CharField(label='Last Name', max_length=20)
    email = forms.EmailField(label='Email', required=False)
    address = forms.CharField(label='Mailing Address', max_length=50)
    postal_code = forms.CharField(label='Postal Code', max_length=7)
    city = forms.CharField(label='City', max_length=30)

src/cajn_site/views/base_views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from ..models import Clients

def home(request):
    return render(request, 'site/home.html')

@login_required
def ManageClients(request):
    return render(request, 'site/clients-pages/manage-clients.html', {'all_clients': Clients.objects.all()})

##############################
#   This is will be moved to an invoice view .py file later!
##############################
@login_required
def CreateInvoice(request):
    return render(request, 'site/invoice_generation_pages/invoice.html')

src/cajn_site/views/client_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from ..models import Clients, Vehicle, Parts, Vehicle_Work
from ..forms import AddClientForm, AddWorkDoneForm

@login_required
def AddClientView(request):
    if request.method == 'POST':
        form = AddClientForm(request.POST)
    else:
        form = AddClientForm()

    # render the page to the browser passing in vehcile information and the form needed
    page = render(request, 'site/add-info-pages/add-client.html', {'vehicle_list': Vehicle.objects.all(), 'form': form})
    if form.is_valid():
        if Vehicle.objects.count() > 0:
            add_vehicle = request.POST["vehicles"]
            if add_vehicle != "null":
                AddClient_vehicle(form, add_vehicle)
                return redirect('cajn-manage-clients')

        AddClient(form)
        # return back to the main home page
        return redirect('cajn-manage-clients')

    # default return
    return page

def AddClient_vehicle(form, add_vehicle):
    new_client = AddClient(form)
    new_client.vehicles.add(add_vehicle)

def AddClient(form):
    # get the cleaned data from the form and create a new object using said data
    new_client = Clients.objects.create(client_f_name = form.cleaned_data["first_name"], client_l_name = form.cleaned_data["last_name"], 
                                client_email = form.cleaned_data["email"], mailing_address = form.cleaned_data["address"], 
                                postal_code = form.cleaned_data["postal_code"], city = form.cleaned_data["city"])
    return new_client


@login_required
def ClientManagePage(request, client_id):
    return render(request, 'site/clients-pages/client-info.html', {'client_info': Clients.objects.get(pk = client_id)})

@login_required
def DeleteClient(request, id):
    client_info = Clients.objects.get(pk = id)
    client_info.delete()
    return redirect('cajn-manage-clients')


@login_required
def AddVehicleToClient(request, id):
    return render(request, 'site/clients-pages/add-vehicle-to-client.html', {'vehicle_list': Vehicle.objects.all(), 'client_info': Clients.objects.get(pk = id)})

def AddVehicleClient_FormRequest(request, id):
    vehicle_id = request.POST['vehicles']

    if vehicle_id != "null":
        UpdateClientById(id, vehicle_id)

    return redirect('cajn-client', id)

def UpdateClientById(id, vehicle_id):
    Clients.objects.get(pk = id).vehicles.add(vehicle_id)

# find a way to clean this code up
def ReturnClientInfoList():
    info = [Clients._meta.get_field('client_f_name'), Clients._meta.get_field('client_l_name'), Clients._meta.get_field('client_email'),
            Clients._meta.get_field('mailing_address'), Clients._meta.get_field('postal_code'), Clients._meta.get_field('city')]
    return info

@login_required
def EditClient(request, id):
    client = Clients.objects.get(pk = id)
    field_objects = ReturnClientInfoList()

    if request.method == 'POST':
        form = AddClientForm(request.POST)
    else: 
        # currently doesn't work, might have to hard code in html tags
        form = AddClientForm(initial={'first_name': getattr(client, field_objects[0].attname), 'last_name': getattr(client, field_objects[1].attname),
                                    'email': getattr(client, field_objects[2].attname), 'address': getattr(client, field_objects[3].attname),
                                    'postal_code': getattr(client, field_objects[4].attname), 'city': getattr(client, field_objects[5].attname)})

    page = render(request, 'site/clients-pages/edit-client-info.html', {'form': form})

    if form.is_valid():
        Clients.objects.filter(pk = id).update(client_f_name = form.cleaned_data["first_name"], client_l_name = form.cleaned_data["last_name"], 
                        client_email = form.cleaned_data["email"], mailing_address = form.cleaned_data["address"], 
                        postal_code = form.cleaned_data["postal_code"], city = form.cleaned_data["city"])

        return redirect('cajn-client', id)

    return page

src/cajn_site/views/part_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from ..models import Parts
from ..forms import AddPartForm

@login_required
def AddPartView(request):
    if request.method == 'POST':
        form = AddPartForm(request.POST)
    else:
        form = AddPartForm()

    data_type = "Part"
    page = render(request, 'site/add-info-pages/add-info-by-type.html', {'form': form, 'type':data_type})

    if form.is_valid():
        Parts.objects.create(part_name = form.cleaned_data["part_name"], part_serial = request.POST["part_serial_num"])
        return redirect('cajn-manage-clients')

    return page

src/cajn_site/views/vehicle_views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from datetime import datetime

from ..models import Vehicle, Clients, Vehicle_Work
from ..forms import AddVehicleForm, AddWorkDoneForm

@login_required
def AddVehicleView(request):
    if request.method == 'POST':
        form = AddVehicleForm(request.POST)
    else:
        form = AddVehicleForm()

    data_type = "Vehicle"
    page = render(request, 'site/add-info-pages/add-info-by-type.html', {'form': form, 'type':data_type})

    if form.is_valid():
        Vehicle.objects.create(vehicle_brand = form.cleaned_data["vehicle_brand"], vehicle_type = request.POST["vehicle_type"])
        return redirect('cajn-manage-clients')

    return page

@login_required
def VehicleInfoPage(request, client_id, vehicle_id):
    client = Clients.objects.get(pk = client_id)
    vehicle = Vehicle.objects.get(pk = vehicle_id)

    try:
        # get the work that has been done on the vehicle owned by the client
        work_done = Vehicle_Work.objects.filter(client_id = client_id, vehicle_id=vehicle_id)
    except Vehicle_Work.DoesNotExist:
        work_done = "null"

    if request.method == 'POST':
        form = AddWorkDoneForm(request.POST)
    else:
        form = AddWorkDoneForm()

    return render(request, 'site/clients-pages/vehicle-info-page.html', {'client_info': client, "vehicle_info": vehicle, 'work':work_done})

@login_required
def AddWorkDone(request, client_id, vehicle_id):
    vehcile = Vehicle.objects.get(pk = vehicle_id)
    client = Clients.objects.get(pk = client_id)

    if request.method == 'POST':
        form = AddWorkDoneForm(request.POST)
    else:
        form = AddWorkDoneForm()

    data_type = "Work"
    page = render(request, 'site/add-info-pages/add-info-by-type.html', {'form': form, 'type':data_type})

    if form.is_valid():
        Vehicle_Work.objects.create(title = datetime.today, vehicle_id = vehcile, client_id = client, last_service_date = form.cleaned_data['last_service_date'], last_service_hours = form.cleaned_data['last_service_hours'], work_done = form.cleaned_data['work_done'])
        return redirect('cajn-manage-clients')

    return page

src/cajn_site/templates/site/clients-pages/add-vehicle-to-client.html
{% extends 'site/base-with-nav.html' %}

{% block title %}Add Vehicle to {{client_info.client_f_name}}{%endblock%}

{% block content %}
<form method="POST" action="/client-vehicle/{{client_info.id}}">
    {% csrf_token %}
    <fieldset>
        <legend>Add Vehicle To {{client_info.client_f_name}} {{client_info.client_l_name}}</legend>
            <label for="id_vehicles">Add Vehicle</label>
            <select name="vehicles">
                <option value="null">-------</option>
                {% if vehicle_list.count != 0 %}
                    {% for v in vehicle_list %}
                        <option value="{{v.id}}">{{v.vehicle_brand}} {{v.vehicle_type}}</option>
                    {% endfor %}
                {% endif %}
            </select>
    </fieldset>
    <input type="submit" value="Add to Client">
</form>
{% endblock %}

src/cajn_site/templates/site/clients-pages/client-info.html
{% extends 'site/base-with-nav.html' %}

{% block title %}Client - {{client_info.client_f_name}}{% endblock %}

{% block content %}
    <h1>Getting information for: {{client_info.client_f_name}} {{client_info.client_l_name}}</h1>
    <form action="/EditClient/{{client_info.id}}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Edit">
    </form>
    <h3>Email: <a style="font-weight:normal;">{{client_info.client_email}}</a></h3>
    <h3>Mailing Address:</h3>
    <a style="font-weight:normal;">
        {{client_info.mailing_address}} <br/>
        {{client_info.city}}, {{client_info.postal_code}}
    </a>

    <h1>Vehicles:  <form method="POST" action="/AddVehicleClient/{{client_info.id}}">{% csrf_token %} <input type="submit" value="Add New Vehicle"></form></h1>
    {% for v in client_info.vehicles.all %}
        <a href="/vehicle-info/{{client_info.id}}/{{v.id}}">{{ v.vehicle_brand }} {{ v.vehicle_type }}</a>
        <br/>
    {% endfor %}

    <br><br>

    <form action="/DeleteClient/{{client_info.id}}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete Client">
    </form>
{% endblock %}

src/cajn_site/templates/site/clients-pages/edit-client-info.html
{% extends 'site/base-with-nav.html' %}

{% block title %}Edit Client{% endblock %}

{% block content %}
<h1>*** This is work in progress! ***</h1>

<form method="POST">
    {% csrf_token %}
    <fieldset>
        <legend>Edit Client</legend>
        {{ form.non_field_errors }}
        {% for field in form %}
        <div>
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Update">
</form>
{% endblock %}

src/cajn_site/templates/site/clients-pages/manage-clients.html
{% extends 'site/base-with-nav.html' %}

{% block title %} Manage Clients {% endblock %}

{% block content %}
    <h1>Manage Clients</h1>
    
    <h4>Names:</h4>

    {% for clients in all_clients %}
        <li><a href="/client-info/{{clients.id}}">{{ clients.client_f_name }} {{clients.client_l_name}}</a></li>
    {% endfor %}
{% endblock %}

src/cajn_site/templates/site/clients-pages/vehicle-info-page.html
{% extends 'site/base-with-nav.html' %}

{% block title %}Client - {{client_info.client_f_name}}{% endblock %}

{% block content %}
    <h1>Showing work done to vehicle {{vehicle_info.vehicle_brand}} {{vehicle_info.vehicle_type}}</h1>
    <h3><a href="{% url 'cajn-work-done' client_info.id vehicle_info.id %}">Add new work</a></h3>
    <!-- loop through the list of work done to the vehicle stored in the database -->
    {% if work != "null" %}
        <h1>Work we found for {{client_info.client_f_name}} {{client_info.client_l_name}} for 
        vehicle '{{vehicle_info.vehicle_brand}} {{vehicle_info.vehicle_type}}'!</h1>
        {% for w in work %}
            <h4><a href="#">Date - {{w.title}}</a></h4>
        {% endfor %}
    {% else %}
        <h1>No work to display</h1>    
    {% endif %}
{% endblock %}